-- ================================================================
-- MAKNANAME — Complete PostgreSQL Database
-- Host gratis: supabase.com | neon.tech | railway.app
-- ================================================================

-- ================================================================
-- SCHEMA TABLES
-- ================================================================

CREATE TABLE IF NOT EXISTS nama_dasar (
  id              SERIAL PRIMARY KEY,
  nama            VARCHAR(120) UNIQUE NOT NULL,
  asal_bahasa     VARCHAR(60),
  kode_bahasa     CHAR(5),
  makna_singkat   VARCHAR(400),
  makna_detail    TEXT,
  arti_arab       VARCHAR(300),
  transliterasi   VARCHAR(150),
  gender          CHAR(1) DEFAULT 'N',   -- L / P / N
  kategori        VARCHAR(60),
  agama           VARCHAR(40) DEFAULT 'Universal',
  suku            VARCHAR(40),
  sifat_positif   TEXT[],
  sifat_perhatian TEXT[],
  numerologi      INT,
  popularitas     INT DEFAULT 0,
  sumber          VARCHAR(20) DEFAULT 'manual',
  terverifikasi   BOOLEAN DEFAULT TRUE,
  dibuat_pada     TIMESTAMPTZ DEFAULT NOW(),
  diperbarui_pada TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cache_analisis (
  id              SERIAL PRIMARY KEY,
  nama_lengkap    VARCHAR(400) UNIQUE NOT NULL,
  nama_hash       VARCHAR(64) UNIQUE NOT NULL,
  hasil_json      JSONB NOT NULL,
  jumlah_akses    INT DEFAULT 1,
  sumber          VARCHAR(20) DEFAULT 'ai',
  dibuat_pada     TIMESTAMPTZ DEFAULT NOW(),
  terakhir_akses  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS log_pencarian (
  id           SERIAL PRIMARY KEY,
  nama_dicari  VARCHAR(400),
  durasi_ms    INT,
  sumber       VARCHAR(20),
  waktu        TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_nama_lower     ON nama_dasar(LOWER(nama));
CREATE INDEX IF NOT EXISTS idx_nama_kategori  ON nama_dasar(kategori);
CREATE INDEX IF NOT EXISTS idx_nama_gender    ON nama_dasar(gender);
CREATE INDEX IF NOT EXISTS idx_popularitas    ON nama_dasar(popularitas DESC);
CREATE INDEX IF NOT EXISTS idx_cache_hash     ON cache_analisis(nama_hash);
CREATE INDEX IF NOT EXISTS idx_cache_akses    ON cache_analisis(terakhir_akses DESC);

-- Auto-update timestamp trigger
CREATE OR REPLACE FUNCTION fn_update_timestamp()
RETURNS TRIGGER AS $$
BEGIN NEW.diperbarui_pada = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_nama_timestamp ON nama_dasar;
CREATE TRIGGER trg_nama_timestamp
  BEFORE UPDATE ON nama_dasar
  FOR EACH ROW EXECUTE FUNCTION fn_update_timestamp();

-- ================================================================
-- VIEWS
-- ================================================================

CREATE OR REPLACE VIEW v_statistik AS
SELECT
  COUNT(*)                                          AS total_nama,
  COUNT(DISTINCT asal_bahasa)                       AS jumlah_bahasa,
  SUM(CASE WHEN gender='L' THEN 1 ELSE 0 END)      AS nama_laki,
  SUM(CASE WHEN gender='P' THEN 1 ELSE 0 END)      AS nama_perempuan,
  SUM(CASE WHEN gender='N' THEN 1 ELSE 0 END)      AS nama_netral,
  SUM(CASE WHEN terverifikasi THEN 1 ELSE 0 END)   AS terverifikasi,
  SUM(CASE WHEN sumber='ai' THEN 1 ELSE 0 END)     AS dari_ai
FROM nama_dasar;

CREATE OR REPLACE VIEW v_cache_stats AS
SELECT
  COUNT(*)          AS total_cache,
  SUM(jumlah_akses) AS total_akses,
  MAX(terakhir_akses) AS terakhir_pencarian
FROM cache_analisis;

-- ================================================================
-- SEED DATA — 800+ Nama Indonesia Lengkap & Valid
-- ================================================================

INSERT INTO nama_dasar
  (nama, asal_bahasa, kode_bahasa, makna_singkat, makna_detail, arti_arab, transliterasi, gender, kategori, agama, suku, sifat_positif, sifat_perhatian, popularitas)
VALUES

-- ================================================================
-- NAMA ARAB / ISLAMI — LAKI-LAKI
-- ================================================================
('Muhammad','Arab','ar','Yang terpuji, yang diagungkan','Muhammad berasal dari akar kata Arab "hamida" bermakna memuji. Nama Nabi dan Rasul terakhir umat Islam, menjadi nama paling banyak dipakai di dunia. Mengandung harapan agar pemakainya menjadi pribadi yang senantiasa dipuji karena kemuliaan akhlaknya.','مُحَمَّد','Muḥammad','L','Islami','Islam',NULL,ARRAY['Berwibawa','Pemimpin','Karismatik','Dihormati'],ARRAY['Beban ekspektasi tinggi','Perfeksionis'],10000),
('Ahmad','Arab','ar','Yang paling terpuji','Ahmad adalah bentuk superlatif dari "hamida", bermakna yang paling banyak dipuji. Disebutkan dalam Al-Quran surah As-Shaff ayat 6 sebagai nama Nabi Muhammad SAW yang lain. Melambangkan puncak kemuliaan akhlak.','أَحْمَد','Aḥmad','L','Islami','Islam',NULL,ARRAY['Mulia','Terpuji','Berwibawa','Jujur'],ARRAY['Idealis','Terlalu serius'],9000),
('Ali','Arab','ar','Yang tinggi, luhur, mulia','Ali berasal dari kata Arab "ala" bermakna tinggi atau mulia. Nama Ali bin Abi Thalib, sepupu dan menantu Nabi Muhammad SAW, khalifah keempat Islam, simbol keberanian dan kebijaksanaan.','عَلِيّ','ʿAlī','L','Islami','Islam',NULL,ARRAY['Berani','Bijaksana','Pemimpin','Kuat'],ARRAY['Dominan','Keras kepala'],8500),
('Umar','Arab','ar','Panjang umur, makmur, berbuah','Umar berasal dari kata Arab "amara" bermakna hidup panjang dan makmur. Identik dengan Umar bin Khattab, khalifah kedua Islam yang terkenal atas keadilan dan ketegasannya memimpin umat.','عُمَر','ʿUmar','L','Islami','Islam',NULL,ARRAY['Tegas','Adil','Pemimpin','Berani'],ARRAY['Keras','Kurang sabar'],7000),
('Utsman','Arab','ar','Anak burung elang, pemuda gagah','Utsman berasal dari kata Arab yang merujuk pada anak burung elang muda. Nama khalifah ketiga Islam, Utsman bin Affan, yang dikenal sangat dermawan dan berhasil menghimpun Al-Quran dalam satu mushaf.','عُثْمَان','ʿUthmān','L','Islami','Islam',NULL,ARRAY['Dermawan','Pemimpin','Lembut','Berpengaruh'],ARRAY['Terlalu lunak','Mudah dipengaruhi'],5000),
('Ibrahim','Arab','ar','Bapak bangsa-bangsa yang mulia','Ibrahim berasal dari bahasa Ibrani bermakna bapak banyak bangsa. Nabi Allah yang dikenal sebagai bapak para nabi, simbol keimanan teguh dan ketundukan mutlak kepada Allah SWT.','إِبْرَاهِيم','Ibrāhīm','L','Islami','Islam',NULL,ARRAY['Teguh','Ikhlas','Bijaksana','Berwibawa'],ARRAY['Idealis','Sulit dikritik'],6500),
('Yusuf','Arab','ar','Allah akan menambah dan mengangkat derajat','Yusuf berasal dari bahasa Ibrani bermakna Allah akan menambah. Nabi yang dikisahkan dalam Al-Quran sebagai manusia dengan kisah terbaik, dikenal atas kesabaran, kejujuran, dan ketampanannya.','يُوسُف','Yūsuf','L','Islami','Islam',NULL,ARRAY['Sabar','Tampan','Jujur','Bijaksana'],ARRAY['Terlalu percaya orang','Sensitif'],7500),
('Musa','Arab','ar','Ditarik dari air, yang diselamatkan','Musa berasal dari bahasa Mesir Kuno yang bermakna ditarik dari air. Nabi besar yang diutus Allah kepada Firaun, dikenal atas keberaniannya membebaskan Bani Israil dan menerima wahyu Taurat.','مُوسَى','Mūsā','L','Islami','Islam',NULL,ARRAY['Berani','Teguh','Pemimpin','Pelindung'],ARRAY['Terlalu emosional','Impulsif'],6000),
('Isa','Arab','ar','Yang menyelamatkan, Allah adalah keselamatan','Isa adalah nama Nabi Isa dalam tradisi Islam. Berasal dari bahasa Aram bermakna keselamatan. Nabi yang dikenal atas mukjizat menyembuhkan orang sakit dan menghidupkan yang mati atas izin Allah.','عِيسَى','ʿĪsā','L','Islami','Islam',NULL,ARRAY['Penyembuh','Lembut','Penuh kasih','Bijaksana'],ARRAY['Terlalu idealis','Sulit dipahami'],5500),
('Hasan','Arab','ar','Yang baik, indah, tampan','Hasan berasal dari kata Arab "hasuna" bermakna baik atau indah. Nama cucu Nabi Muhammad SAW dari Fatimah dan Ali. Melambangkan kebaikan hati dan keindahan akhlak yang tulus.','حَسَن','Ḥasan','L','Islami','Islam',NULL,ARRAY['Baik hati','Ramah','Dermawan','Sabar'],ARRAY['Terlalu mengalah','Mudah dimanfaatkan'],5500),
('Husain','Arab','ar','Yang baik, tampan, kecil yang indah','Husain adalah bentuk kecil dari Hasan, bermakna yang sangat baik dan tampan. Cucu kedua Nabi Muhammad SAW yang terkenal karena keberaniannya menegakkan kebenaran hingga syahid di Karbala.','حُسَيْن','Ḥusayn','L','Islami','Islam',NULL,ARRAY['Berani','Berprinsip','Mulia','Syahid kebenaran'],ARRAY['Keras dalam prinsip','Sulit berkompromi'],5000),
('Abdullah','Arab','ar','Hamba Allah, yang mengabdi kepada Allah','Abdullah berasal dari kata Arab "abd" (hamba) dan "Allah". Salah satu nama paling mulia dalam Islam karena menyatakan penghambaan kepada Allah. Nama ayah Nabi Muhammad SAW.','عَبْدُ اللّٰه','ʿAbdullāh','L','Islami','Islam',NULL,ARRAY['Taat','Rendah hati','Mulia','Beriman'],ARRAY['Terlalu tunduk','Kurang asertif'],7000),
('Abdurrahman','Arab','ar','Hamba Yang Maha Pengasih','Abdurrahman berasal dari "abd" (hamba) dan "Rahman" (Yang Maha Pengasih). Nama yang sangat dicintai dalam Islam, melambangkan penghambaan kepada Allah Yang Maha Kasih. Disebut Nabi sebagai nama terbaik.','عَبْدُ الرَّحْمٰن','ʿAbdu r-Raḥmān','L','Islami','Islam',NULL,ARRAY['Penuh kasih','Mulia','Taat','Dermawan'],ARRAY['Terlalu lembut','Sulit tegas'],6500),
('Rizki','Arab','ar','Rezeki, karunia Allah','Rizki berasal dari kata Arab "rizq" bermakna rezeki atau karunia dari Allah. Mengandung harapan agar anak selalu diberkahi rezeki berlimpah dan menjadi sumber kebaikan bagi lingkungannya.','رِزْقِي','Rizqī','L','Islami','Islam',NULL,ARRAY['Beruntung','Dermawan','Bersyukur','Murah hati'],ARRAY['Boros','Kurang hemat'],8000),
('Fajar','Arab','ar','Fajar, cahaya subuh, awal yang cerah','Fajar berasal dari kata Arab "fajr" bermakna waktu fajar atau subuh. Melambangkan awal yang cerah, semangat baru, dan jiwa yang senantiasa membawa harapan layaknya fajar menyingsing.','فَجْر','Fajr','L','Islami','Islam',NULL,ARRAY['Optimis','Semangat','Segar','Pemberi harapan'],ARRAY['Impulsif','Kurang sabar'],6000),
('Fikri','Arab','ar','Pemikiran mendalam, intelektual','Fikri berasal dari kata Arab "fikr" bermakna pikiran atau pemikiran. Melambangkan seseorang yang gemar berpikir, cerdas secara intelektual, dan suka menganalisis sesuatu secara mendalam.','فِكْرِي','Fikrī','L','Islami','Islam',NULL,ARRAY['Cerdas','Analitis','Inovatif','Bijaksana'],ARRAY['Overthinking','Kurang spontan'],4500),
('Naufal','Arab','ar','Pemuda tampan dan dermawan','Naufal berasal dari kata Arab bermakna pemuda tampan dan dermawan. Melambangkan jiwa yang besar, murah hati, dan penampilan yang menawan hati siapa pun yang melihatnya.','نَوْفَل','Nawfal','L','Islami','Islam',NULL,ARRAY['Dermawan','Tampan','Berwibawa','Murah hati'],ARRAY['Egois','Terlalu percaya diri'],5000),
('Rafi','Arab','ar','Yang tinggi derajatnya, yang diangkat','Rafi berasal dari kata Arab "rafa" bermakna mengangkat atau meninggikan. Ar-Rafi adalah salah satu Asmaul Husna. Mengandung doa agar anak mencapai derajat tinggi di sisi Allah dan manusia.','رَافِع','Rāfiʿ','L','Islami','Islam',NULL,ARRAY['Berambisi','Sukses','Berwibawa','Dihormati'],ARRAY['Sombong','Sulit merendah'],7000),
('Zaki','Arab','ar','Cerdas, suci, bersih hatinya','Zaki berasal dari kata Arab "zaka" bermakna suci, bersih, atau cerdas. Mengandung makna kemurnian hati sekaligus kecerdasan pikiran. Nama ideal untuk anak yang diharapkan tumbuh bersih dan pandai.','ذَكِي','Dhakī','L','Islami','Islam',NULL,ARRAY['Cerdas','Suci hati','Jujur','Teliti'],ARRAY['Perfeksionis','Sulit memaafkan'],5500),
('Farhan','Arab','ar','Yang gembira, bahagia, riang','Farhan berasal dari kata Arab "faraha" bermakna gembira atau bahagia. Mengandung harapan agar anak senantiasa membawa kebahagiaan bagi dirinya sendiri dan orang-orang di sekitarnya.','فَرْحَان','Farḥān','L','Islami','Islam',NULL,ARRAY['Ceria','Optimis','Menyenangkan','Ramah'],ARRAY['Kurang serius','Terlalu santai'],6000),
('Hafiz','Arab','ar','Penjaga, penghafal Al-Quran','Hafiz berasal dari kata Arab "hafiza" bermakna menjaga atau menghafal. Al-Hafiz adalah Asmaul Husna bermakna Maha Menjaga. Juga merujuk pada gelar bagi penghafal 30 juz Al-Quran.','حَافِظ','Ḥāfiẓ','L','Islami','Islam',NULL,ARRAY['Setia','Dapat dipercaya','Teliti','Disiplin'],ARRAY['Kaku','Sulit berubah'],5000),
('Taufik','Arab','ar','Petunjuk sukses, kemudahan dari Allah','Taufik berasal dari kata Arab "tawfiq" bermakna petunjuk menuju kesuksesan yang diberikan Allah. Doa agar anak mendapat kemudahan dari Allah dalam setiap langkah hidupnya.','تَوْفِيق','Tawfīq','L','Islami','Islam',NULL,ARRAY['Sukses','Dibimbing Allah','Mudah','Beruntung'],ARRAY['Menggantungkan keberuntungan','Kurang usaha'],6000),
('Ikhsan','Arab','ar','Kebaikan, kesempurnaan, berbuat baik','Ikhsan berasal dari kata Arab "ahsana" bermakna berbuat kebaikan atau kesempurnaan. Dalam Islam, ihsan adalah tingkat ibadah tertinggi yaitu beribadah seolah melihat Allah atau merasa dilihat Allah.','إِحْسَان','Iḥsān','L','Islami','Islam',NULL,ARRAY['Baik hati','Teliti','Taat','Sempurna'],ARRAY['Perfeksionis','Sulit puas'],5000),
('Ridho','Arab','ar','Rida, kerelaan, kepuasan hati','Ridho berasal dari kata Arab "ridha" bermakna rida atau kerelaan. Dalam Islam, rida Allah adalah tujuan tertinggi seorang Muslim. Mengandung doa agar anak senantiasa mendapat keridhaan Allah.','رِضَا','Riḍā','L','Islami','Islam',NULL,ARRAY['Puas','Bersyukur','Tenang','Ikhlas'],ARRAY['Terlalu pasrah','Kurang ambisius'],5500),
('Ilham','Arab','ar','Ilham, inspirasi, bisikan hati','Ilham berasal dari kata Arab bermakna ilham atau inspirasi yang diturunkan ke dalam hati. Melambangkan seseorang yang penuh inspirasi, kreatif, dan mampu menginspirasi orang lain.','إِلْهَام','Ilhām','L','Islami','Islam',NULL,ARRAY['Kreatif','Inspiratif','Intuitif','Visioner'],ARRAY['Tidak realistis','Sulit fokus'],6000),
('Wahyu','Arab/Jawa','ar','Wahyu ilahi, petunjuk dari Tuhan','Wahyu berasal dari kata Arab "wahy" bermakna wahyu atau petunjuk dari Allah kepada para nabi. Dalam tradisi Jawa juga bermakna petunjuk spiritual. Melambangkan jiwa yang terbimbing cahaya ilahi.','وَحْي','Waḥy','L','Islami','Islam','Jawa',ARRAY['Spiritual','Bijaksana','Dipercaya','Intuitif'],ARRAY['Terlalu idealis','Sulit pragmatis'],7000),
('Daffa','Arab','ar','Pelindung, yang membela, perisai','Daffa berasal dari kata Arab "dafa" bermakna menolak atau melindungi. Melambangkan seseorang yang menjadi pelindung bagi orang-orang yang dicintainya dan mampu menangkis segala bahaya.','دَافِع','Dāfiʿ','L','Islami','Islam',NULL,ARRAY['Pelindung','Kuat','Setia','Berani'],ARRAY['Protektif berlebihan','Posesif'],6000),
('Raihan','Arab','ar','Tanaman harum surga, rejeki yang baik','Raihan berasal dari kata Arab bermakna tanaman harum yang tumbuh di surga. Melambangkan keharuman nama dan kebaikan rezeki yang mengalir bagaikan aroma bunga surga.','رَيْحَان','Rayḥān','L','Islami','Islam',NULL,ARRAY['Harum','Beruntung','Menyenangkan','Baik'],ARRAY['Terlalu perfeksionis','Sulit menerima kekurangan'],5500),
('Faisal','Arab','ar','Pemisah antara kebenaran dan kebatilan','Faisal berasal dari kata Arab "fasala" bermakna pemisah atau penentu. Melambangkan seseorang yang tegas dan mampu membedakan serta memisahkan antara yang benar dan yang salah.','فَيْصَل','Fayṣal','L','Islami','Islam',NULL,ARRAY['Tegas','Adil','Pemimpin','Bijaksana'],ARRAY['Keras','Kurang empati'],5500),
('Rizal','Arab','ar','Pemuda gagah, lelaki yang hebat','Rizal berasal dari kata Arab "rijal" bermakna para lelaki atau pemuda gagah. Nama yang sangat populer di Indonesia dan Malaysia, melambangkan kejantanan dan semangat pemuda.','رِجَال','Rijāl','L','Islami','Islam',NULL,ARRAY['Gagah','Bersemangat','Mandiri','Berani'],ARRAY['Keras kepala','Impulsif'],7000),
('Maulana','Arab','ar','Tuan kami, pemimpin kami yang dimuliakan','Maulana berasal dari kata Arab "mawlana" bermakna tuan atau pemimpin kami. Gelar kehormatan untuk ulama besar. Melambangkan kepemimpinan spiritual dan keilmuan yang dimuliakan.','مَوْلَانَا','Mawlānā','L','Islami','Islam',NULL,ARRAY['Pemimpin','Dihormati','Berwibawa','Karismatik'],ARRAY['Otoriter','Sulit dikoreksi'],5000),
('Anwar','Arab','ar','Cahaya yang terang benderang, bersinar','Anwar berasal dari kata Arab "anwara" bermakna cahaya atau yang paling terang benderang. Melambangkan jiwa yang penuh cahaya, menerangi kegelapan dan memberi harapan kepada sekitarnya.','أَنْوَر','Anwar','L','Islami','Islam',NULL,ARRAY['Bercahaya','Menginspirasi','Hangat','Cerdas'],ARRAY['Terlalu bersinar','Sulit rendah hati'],5000),
('Syarif','Arab','ar','Yang mulia, bangsawan, terhormat','Syarif berasal dari kata Arab bermakna mulia, bangsawan, atau yang terhormat. Gelar keturunan Nabi Muhammad SAW. Melambangkan kemuliaan nasab dan akhlak yang tinggi.','شَرِيف','Sharīf','L','Islami','Islam',NULL,ARRAY['Mulia','Terhormat','Berdarah biru','Berwibawa'],ARRAY['Merasa superior','Sulit membumi'],4500),
('Zaidan','Arab','ar','Pertumbuhan, bertambah baik, berkembang','Zaidan berasal dari kata Arab "zada" bermakna bertambah atau tumbuh. Mengandung harapan agar anak terus berkembang dalam ilmu, rezeki, akhlak, dan prestasi tanpa henti.','زَيْدَان','Zaydān','L','Islami','Islam',NULL,ARRAY['Berkembang','Progresif','Tekun','Terus maju'],ARRAY['Tidak pernah puas','Workaholic'],6000),
('Nabil','Arab','ar','Yang mulia, terhormat, bangsawan','Nabil berasal dari kata Arab "nabala" bermakna mulia atau terhormat. Melambangkan kemuliaan budi pekerti dan keluhuran akhlak yang menjadi panutan bagi orang-orang di sekitarnya.','نَبِيل','Nabīl','L','Islami','Islam',NULL,ARRAY['Mulia','Terhormat','Elegan','Berwibawa'],ARRAY['Angkuh','Terlalu formal'],5500),
('Wahid','Arab','ar','Yang satu, tunggal, tiada duanya','Wahid berasal dari kata Arab "wahid" bermakna satu atau tunggal. Al-Wahid adalah Asmaul Husna bermakna Maha Esa. Mengandung makna keunikan dan keistimewaan yang tidak ada duanya.','وَاحِد','Wāḥid','L','Islami','Islam',NULL,ARRAY['Unik','Mandiri','Istimewa','Orisinal'],ARRAY['Sulit bergaul','Eksentrik'],4500),
('Kamil','Arab','ar','Yang sempurna, yang lengkap','Kamil berasal dari kata Arab "kamila" bermakna sempurna atau lengkap. Melambangkan seseorang yang memiliki sifat-sifat mulia secara menyeluruh dan lengkap dalam segala aspek kehidupan.','كَامِل','Kāmil','L','Islami','Islam',NULL,ARRAY['Sempurna','Lengkap','Teliti','Unggul'],ARRAY['Perfeksionis','Sulit menerima kekurangan'],4000),
('Ghani','Arab','ar','Yang kaya, berkecukupan, tidak membutuhkan','Ghani berasal dari kata Arab bermakna kaya atau berkecukupan. Al-Ghani adalah Asmaul Husna. Mengandung doa agar anak selalu berkecukupan dalam segala hal lahir dan batin.','غَنِي','Ghanī','L','Islami','Islam',NULL,ARRAY['Kaya','Berkecukupan','Dermawan','Mandiri'],ARRAY['Sombong','Kurang empati kepada miskin'],4000),
('Asyraf','Arab','ar','Yang paling mulia, yang paling terhormat','Asyraf adalah bentuk superlatif dari Syarif, bermakna yang paling mulia. Mengandung harapan tertinggi agar anak menjadi manusia paling mulia akhlaknya di antara orang-orang sekitarnya.','أَشْرَف','Ashraf','L','Islami','Islam',NULL,ARRAY['Sangat mulia','Terhormat','Pemimpin','Berpengaruh'],ARRAY['Sulit merendah','Ekspektasi tinggi'],4000),
('Bilal','Arab','ar','Yang selalu membasahi, yang menyegarkan','Bilal berasal dari kata Arab bermakna membasahi atau menyegarkan. Nama sahabat Nabi Muhammad SAW, Bilal bin Rabah, muazin pertama dalam Islam yang terkenal atas keteguhannya dalam keimanan.','بِلَال','Bilāl','L','Islami','Islam',NULL,ARRAY['Teguh','Berani','Setia','Kuat'],ARRAY['Keras kepala','Sulit menyerah'],4500),
('Salman','Arab','ar','Yang selamat, yang tenteram','Salman berasal dari kata Arab "salima" bermakna selamat atau tenteram. Nama sahabat Nabi, Salman Al-Farisi, yang terkenal atas kecerdasannya dan keloyalannya kepada Islam.','سَلْمَان','Salmān','L','Islami','Islam',NULL,ARRAY['Selamat','Cerdas','Loyal','Bijaksana'],ARRAY['Lambat memutuskan','Terlalu berhati-hati'],4000),
('Harun','Arab','ar','Yang tinggi, yang bergunung, pemimpin','Harun berasal dari bahasa Ibrani bermakna gunung yang tinggi atau pemimpin. Nabi Allah, saudara Nabi Musa, yang dikenal atas keahlian berbicara dan kepemimpinannya.','هَارُون','Hārūn','L','Islami','Islam',NULL,ARRAY['Pemimpin','Komunikatif','Bijaksana','Kuat'],ARRAY['Bergantung pada orang lain','Kurang mandiri'],4500),
('Idris','Arab','ar','Yang gemar belajar, yang rajin mempelajari','Idris berasal dari kata Arab "darasa" bermakna belajar atau mempelajari. Nabi Allah yang dikenal sebagai orang pertama yang menulis dengan pena dan menjahit pakaian dalam sejarah manusia.','إِدْرِيس','Idrīs','L','Islami','Islam',NULL,ARRAY['Cerdas','Rajin belajar','Terampil','Tekun'],ARRAY['Kutu buku','Kurang sosial'],4000),

-- ================================================================
-- NAMA ARAB / ISLAMI — PEREMPUAN
-- ================================================================
('Siti','Arab','ar','Nyonya, wanita mulia, tuan putri','Siti berasal dari kata Arab "sayyidati" bermakna nyonya atau wanita terhormat. Nama paling umum dipakai untuk perempuan Muslim Indonesia. Sering dikombinasikan dengan nama lain sebagai tanda kemuliaan.','سِيتِي','Sītī','P','Islami','Islam',NULL,ARRAY['Anggun','Terhormat','Mulia','Lembut'],ARRAY['Terlalu formal','Konservatif'],10000),
('Fatimah','Arab','ar','Yang menyapih, menjauhkan dari kejahatan','Fatimah berasal dari kata Arab "fatama" bermakna menyapih. Nama putri Nabi Muhammad SAW yang paling dicintai, wanita paling mulia dalam Islam. Simbol kesabaran, keteguhan, dan kemuliaan.','فَاطِمَة','Fāṭimah','P','Islami','Islam',NULL,ARRAY['Sabar','Mulia','Kuat','Pengasih'],ARRAY['Terlalu berkorban','Kurang mementingkan diri'],9000),
('Aisyah','Arab','ar','Yang hidup penuh semangat','Aisyah berasal dari kata Arab "asha" bermakna hidup atau bersemangat. Nama istri tercinta Nabi Muhammad SAW, sumber hadits terbanyak, simbol kecerdasan wanita Muslim sepanjang zaman.','عَائِشَة','ʿĀʾishah','P','Islami','Islam',NULL,ARRAY['Cerdas','Bersemangat','Berani','Penuh warna'],ARRAY['Impulsif','Bicara tanpa dipikir'],8500),
('Nurul','Arab','ar','Cahaya, sinar yang menerangi','Nurul berasal dari kata Arab "nur" bermakna cahaya. Biasanya digunakan sebagai awalan: Nurul Iman, Nurul Hidayah. Melambangkan jiwa yang bercahaya dan menerangi lingkungan sekitarnya.','نُور','Nūr','P','Islami','Islam',NULL,ARRAY['Bercahaya','Menginspirasi','Baik hati','Hangat'],ARRAY['Mudah terpengaruh','Kurang tegas'],9000),
('Zahra','Arab','ar','Bunga, bersinar, bercahaya indah','Zahra berasal dari kata Arab "zahara" bermakna bersinar atau mekar seperti bunga. Az-Zahra adalah julukan Fatimah putri Nabi. Melambangkan kecantikan, keharuman, dan keindahan sejati.','زَهْرَة','Zahrah','P','Islami','Islam',NULL,ARRAY['Cantik','Harum','Menarik','Anggun'],ARRAY['Terlalu memperhatikan penampilan','Sensitif'],7500),
('Rahma','Arab','ar','Kasih sayang, rahmat, belas kasih','Rahma berasal dari kata Arab "rahmah" bermakna kasih sayang atau rahmat. Ar-Rahman adalah Asmaul Husna bermakna Maha Pengasih. Mengandung harapan agar anak tumbuh penuh kasih sayang.','رَحْمَة','Raḥmah','P','Islami','Islam',NULL,ARRAY['Penyayang','Lembut','Empati tinggi','Murah hati'],ARRAY['Mudah menangis','Terlalu empatis'],7000),
('Nadia','Arab','ar','Penuh harapan, titik embun pagi','Nadia berasal dari kata Arab "nida" bermakna panggilan atau seruan, juga berkaitan dengan embun pagi yang segar. Melambangkan harapan, kesegaran, dan kebahagiaan yang disebarkan kepada sekitar.','نَادِيَة','Nādiyah','P','Islami','Islam',NULL,ARRAY['Optimis','Segar','Penuh harapan','Komunikatif'],ARRAY['Idealis','Terlalu berharap'],7000),
('Hana','Arab','ar','Kebahagiaan, kenikmatan hidup','Hana berasal dari kata Arab "hana" bermakna kebahagiaan atau kenikmatan. Nama pendek yang indah, melambangkan kegembiraan dan jiwa yang ringan selalu membawa sukacita bagi orang lain.','هَنَاء','Hanāʾ','P','Islami','Islam',NULL,ARRAY['Bahagia','Riang','Positif','Bersyukur'],ARRAY['Kurang serius','Terlalu santai'],5500),
('Nayla','Arab','ar','Yang mendapat, yang berhasil, yang memperoleh','Nayla berasal dari kata Arab "nala" bermakna mendapat atau memperoleh. Mengandung makna bahwa sang anak akan selalu berhasil mendapatkan apa yang dicita-citakan dalam hidupnya.','نَيْلَة','Naylah','P','Islami','Islam',NULL,ARRAY['Berhasil','Sukses','Tekun','Mandiri'],ARRAY['Terlalu ambisius','Tidak puas'],6500),
('Khairunisa','Arab','ar','Sebaik-baik wanita, wanita terbaik','Khairunisa berasal dari kata Arab "khair" (kebaikan) dan "nisa" (wanita). Bermakna sebaik-baik wanita. Mengandung doa mulia agar anak menjadi wanita terbaik dalam akhlak dan karakternya.','خَيْرُ النِّسَاء','Khairu n-Nisāʾ','P','Islami','Islam',NULL,ARRAY['Mulia','Berakhlak baik','Dermawan','Bijaksana'],ARRAY['Perfeksionis','Kurang fleksibel'],4000),
('Salsabila','Arab','ar','Mata air surga yang mengalir jernih','Salsabila berasal dari kata Arab bermakna mata air jernih yang mengalir di surga, disebutkan dalam Al-Quran surah Al-Insan. Melambangkan kesucian, kejernihan hati, dan keindahan.','سَلْسَبِيل','Salsabīl','P','Islami','Islam',NULL,ARRAY['Jernih','Suci','Lembut','Mengalir'],ARRAY['Terlalu lembut','Mudah terbawa arus'],6000),
('Azizah','Arab','ar','Yang mulia, yang perkasa, yang berharga','Azizah berasal dari kata Arab "aziz" bermakna mulia, perkasa, atau berharga. Al-Aziz adalah Asmaul Husna. Melambangkan wanita yang berharga, kuat, dan mulia dalam segala hal.','عَزِيزَة','ʿAzīzah','P','Islami','Islam',NULL,ARRAY['Mulia','Kuat','Berharga','Berwibawa'],ARRAY['Keras','Sulit menunjukkan kelemahan'],5000),
('Fauziah','Arab','ar','Yang berhasil, yang menang, yang sukses','Fauziah berasal dari kata Arab "fauza" bermakna keberhasilan atau kemenangan. Mengandung doa agar anak senantiasa meraih kemenangan dalam setiap perjuangan kehidupan yang dihadapinya.','فَوْزِيَّة','Fawziyyah','P','Islami','Islam',NULL,ARRAY['Sukses','Pemenang','Ambisius','Gigih'],ARRAY['Terlalu kompetitif','Sulit menerima kekalahan'],4500),
('Halimah','Arab','ar','Yang penyabar, yang lembut hatinya','Halimah berasal dari kata Arab "haluma" bermakna sabar dan lembut. Nama ibu susu Nabi Muhammad SAW, Halimah As-Sadiyah, yang terkenal atas kelembutannya merawat bayi Nabi.','حَلِيمَة','Ḥalīmah','P','Islami','Islam',NULL,ARRAY['Sabar','Lembut','Pengasih','Telaten'],ARRAY['Terlalu sabar','Mudah dizalimi'],4500),
('Wardah','Arab','ar','Bunga mawar, kembang yang harum indah','Wardah berasal dari kata Arab "warda" bermakna bunga mawar atau kembang. Melambangkan keindahan, keharuman, dan kelembutan seorang wanita layaknya mawar yang mekar sempurna.','وَرْدَة','Wardah','P','Islami','Islam',NULL,ARRAY['Indah','Harum','Lembut','Menarik'],ARRAY['Rapuh','Mudah layu di bawah tekanan'],5000),
('Laila','Arab','ar','Malam, kegelapan malam yang indah','Laila berasal dari kata Arab "layl" bermakna malam. Dalam sastra Arab, Laila adalah nama kekasih yang selalu dicari dalam kisah cinta klasik Laila dan Majnun. Melambangkan misteri dan daya tarik.','لَيْلَى','Laylā','P','Islami','Islam',NULL,ARRAY['Misterius','Menarik','Romantis','Penuh perasaan'],ARRAY['Moody','Terlalu emosional'],5000),
('Mariam','Arab','ar','Yang dicintai, yang dikasihi Allah','Mariam berasal dari bahasa Ibrani bermakna yang dicintai atau yang dikasihi. Nama ibunda Nabi Isa, Maryam binti Imran, wanita paling mulia dalam tradisi Islam dan Kristen.','مَرْيَم','Maryam','P','Islami','Islam',NULL,ARRAY['Suci','Mulia','Pengasih','Kuat'],ARRAY['Terlalu menyendiri','Kurang sosial'],5500),
('Khadijah','Arab','ar','Lahir prematur, yang terdahulu','Khadijah berasal dari kata Arab bermakna yang terdahulu atau lahir lebih awal. Nama istri pertama dan paling dicintai Nabi Muhammad SAW, wanita pertama yang masuk Islam, simbol loyalitas dan kekuatan.','خَدِيجَة','Khadījah','P','Islami','Islam',NULL,ARRAY['Loyal','Kuat','Bijaksana','Dermawan'],ARRAY['Protektif berlebihan','Terlalu possessive'],5000),
('Yasmin','Arab','ar','Bunga melati, wangi yang memikat','Yasmin berasal dari kata Arab bermakna bunga melati atau bunga yasmin. Melambangkan keharuman, kelembutan, dan kecantikan alami yang memikat hati siapa pun yang mengenalnya.','يَاسَمِين','Yāsamīn','P','Islami','Islam',NULL,ARRAY['Harum','Lembut','Memikat','Alami'],ARRAY['Rapuh','Kurang tegas'],5500),
('Shafira','Arab','ar','Duta, utusan, yang terhormat','Shafira berasal dari kata Arab "safara" bermakna utusan atau duta. Melambangkan seseorang yang menjadi perantara kebaikan, wakil yang disegani, dan duta yang membawa pesan kebaikan.','سَفِيرَة','Safīrah','P','Islami','Islam',NULL,ARRAY['Berwibawa','Komunikatif','Terhormat','Diplomat'],ARRAY['Terlalu formal','Sulit santai'],5000),

-- ================================================================
-- NAMA JAWA
-- ================================================================
('Budi','Jawa','jv','Budi pekerti, kebijaksanaan, akal budi','Budi adalah nama Jawa bermakna budi pekerti atau akhlak mulia. Dalam filosofi Jawa, budi melambangkan kualitas moral tertinggi — keluhuran budi pekerti yang menjadi panduan dalam bertindak, berucap, dan bersikap.','','','L','Jawa','Universal','Jawa',ARRAY['Bijaksana','Bermoral','Sopan','Dihormati'],ARRAY['Konservatif','Kaku dalam tradisi'],8000),
('Wijaya','Jawa','jv','Kemenangan, kejayaan, keberhasilan','Wijaya berasal dari bahasa Jawa-Sansekerta bermakna kemenangan atau kejayaan. Nama yang sering dipakai sebagai nama belakang keluarga Jawa, melambangkan harapan agar keturunan selalu meraih kejayaan.','','','N','Jawa','Universal','Jawa',ARRAY['Sukses','Ambisius','Pemimpin','Gigih'],ARRAY['Terlalu kompetitif','Sulit menerima kekalahan'],7500),
('Nugroho','Jawa','jv','Anugerah, karunia Tuhan yang indah','Nugroho berasal dari bahasa Jawa bermakna anugerah atau karunia. Mengandung rasa syukur orang tua atas kehadiran anak yang dianggap sebagai anugerah berharga tak ternilai dari Tuhan Yang Maha Esa.','','','L','Jawa','Universal','Jawa',ARRAY['Bersyukur','Rendah hati','Tulus','Dermawan'],ARRAY['Kurang percaya diri','Terlalu merendah'],6500),
('Pertiwi','Jawa','jv','Bumi, ibu pertiwi, tanah air tercinta','Pertiwi berasal dari bahasa Jawa-Sansekerta bermakna bumi atau tanah air. Ibu Pertiwi adalah julukan Indonesia. Nama yang sangat nasionalis mengandung makna cinta tanah air dan kesuburan bumi.','','','P','Jawa','Universal','Jawa',ARRAY['Nasionalis','Kuat','Subur','Membumi'],ARRAY['Keras kepala','Sulit dipengaruhi'],5000),
('Rahayu','Jawa','jv','Selamat, sejahtera, sentosa, bahagia','Rahayu adalah kata Jawa bermakna selamat, sejahtera, atau sentosa. Sering diucapkan sebagai salam dalam bahasa Jawa. Mengandung doa agar pemakainya selalu dalam keadaan selamat dan bahagia.','','','P','Jawa','Universal','Jawa',ARRAY['Tenang','Bahagia','Harmonis','Menenangkan'],ARRAY['Pasif','Kurang ambisius'],6000),
('Wibowo','Jawa','jv','Berwibawa, penuh kewibawaan, berpengaruh','Wibowo berasal dari kata Jawa "wibawa" bermakna kewibawaan. Nama populer di Jawa sebagai nama belakang, melambangkan harapan agar pemakainya menjadi pribadi yang berwibawa dan disegani.','','','L','Jawa','Universal','Jawa',ARRAY['Berwibawa','Disegani','Pemimpin','Berpengaruh'],ARRAY['Kaku','Sulit bercanda'],6500),
('Santoso','Jawa','jv','Tenteram, damai, sentosa, kokoh','Santoso berasal dari kata Jawa "santosa" bermakna tenteram, damai, atau kuat. Mengandung doa agar pemakainya hidup dalam ketentraman dan menjadi sumber kedamaian bagi lingkungannya.','','','L','Jawa','Universal','Jawa',ARRAY['Damai','Tenang','Stabil','Dapat diandalkan'],ARRAY['Pasif','Kurang dinamis'],5000),
('Purnomo','Jawa','jv','Purnama, bulan penuh, sempurna','Purnomo berasal dari kata Jawa "purnama" bermakna bulan purnama. Melambangkan kesempurnaan, kepenuhan, dan cahaya yang terang benderang menerangi kegelapan malam.','','','L','Jawa','Universal','Jawa',ARRAY['Sempurna','Bersinar','Menginspirasi','Penuh'],ARRAY['Perfeksionis','Ekspektasi tinggi'],4500),
('Tri','Jawa','jv','Tiga, ketiga, urutan ketiga','Tri berasal dari bahasa Jawa-Sansekerta bermakna tiga. Sering diberikan kepada anak ketiga dalam keluarga Jawa. Angka tiga dalam filosofi Jawa melambangkan keseimbangan dan kesempurnaan.','','','N','Jawa','Universal','Jawa',ARRAY['Seimbang','Adaptif','Kreatif','Fleksibel'],ARRAY['Kurang identitas kuat','Mudah terpengaruh'],6000),
('Eko','Jawa','jv','Pertama, tunggal, satu-satunya','Eko berasal dari bahasa Jawa-Sansekerta "eka" bermakna satu atau pertama. Diberikan kepada anak pertama keluarga Jawa. Melambangkan keistimewaan sebagai yang pertama, teladan bagi adik-adiknya.','','','L','Jawa','Universal','Jawa',ARRAY['Mandiri','Pemimpin','Bertanggung jawab','Pelopor'],ARRAY['Dominan','Kurang mau mendengar'],7000),
('Dwi','Jawa','jv','Dua, kedua, kembar dalam keseimbangan','Dwi berasal dari bahasa Jawa-Sansekerta "dwi" bermakna dua. Diberikan kepada anak kedua dalam keluarga. Melambangkan keseimbangan, dualitas, dan kemampuan melihat dari dua sudut pandang.','','','N','Jawa','Universal','Jawa',ARRAY['Seimbang','Diplomatis','Penengah','Empatik'],ARRAY['Tidak tegas','Terlalu mengikuti'],6500),
('Sri','Jawa','jv','Dewi kemakmuran, keindahan, kemuliaan','Sri berasal dari bahasa Jawa-Sansekerta merujuk pada Dewi Sri, dewi padi dan kemakmuran dalam mitologi Jawa-Hindu. Mengandung berkah kemakmuran, keindahan, dan kesuburan bumi.','','','P','Jawa','Universal','Jawa',ARRAY['Makmur','Cantik','Mulia','Subur'],ARRAY['Manja','Terlalu bergantung'],9000),
('Endah','Jawa','jv','Indah, cantik, elok rupawan','Endah adalah kata Jawa bermakna indah atau cantik. Mengandung harapan agar pemakainya tumbuh menjadi pribadi yang indah secara lahir maupun batin, menyenangkan hati siapa yang bertemu.','','','P','Jawa','Universal','Jawa',ARRAY['Cantik','Menarik','Menyenangkan','Artistik'],ARRAY['Terlalu memperhatikan penampilan','Sensitif terhadap kritik'],4500),
('Larasati','Jawa','jv','Selaras, harmonis, lembut bagaikan musik','Larasati berasal dari kata Jawa "laras" bermakna selaras atau harmonis, ditambah akhiran "-ati" (hati). Bermakna hati yang selaras dan harmonis. Sering dipakai dalam tradisi seni Jawa.','','','P','Jawa','Universal','Jawa',ARRAY['Harmonis','Artistik','Lembut','Penuh perasaan'],ARRAY['Terlalu sensitif','Mudah tersinggung'],4000),
('Wahyuni','Jawa','jv','Perempuan yang mendapat wahyu ilahi','Wahyuni adalah bentuk feminim dari Wahyu, bermakna perempuan yang mendapat petunjuk atau wahyu dari Tuhan. Melambangkan wanita yang terbimbing cahaya ilahi dalam setiap langkah hidupnya.','','','P','Jawa','Universal','Jawa',ARRAY['Spiritual','Bijaksana','Dipercaya','Intuitif'],ARRAY['Terlalu idealis','Kurang praktis'],5000),
('Setyawati','Jawa','jv','Wanita yang setia, jujur, lurus hatinya','Setyawati berasal dari kata Jawa "setya" bermakna setia atau jujur, ditambah "-wati" (wanita). Tokoh dalam pewayangan, istri Arjuna yang terkenal atas kesetiaan dan kejujurannya.','','','P','Jawa','Universal','Jawa',ARRAY['Setia','Jujur','Lurus','Dapat dipercaya'],ARRAY['Naif','Mudah dikhianati'],4000),
('Prasetyo','Jawa','jv','Janji, yang ditepati, yang terikat kata','Prasetyo berasal dari kata Jawa bermakna janji atau ikatan kata. Melambangkan seseorang yang selalu menepati janji, memegang teguh komitmen, dan dapat dipercaya kata-katanya.','','','L','Jawa','Universal','Jawa',ARRAY['Menepati janji','Komitmen','Jujur','Bertanggung jawab'],ARRAY['Kaku','Sulit berubah pikiran'],5500),
('Sulistyo','Jawa','jv','Yang baik, yang indah, yang sempurna','Sulistyo berasal dari kata Jawa bermakna yang baik atau yang sempurna. Mengandung harapan agar anak tumbuh menjadi manusia yang sempurna dalam segala aspek kehidupan yang dijalaninya.','','','N','Jawa','Universal','Jawa',ARRAY['Baik','Sempurna','Harmonis','Teliti'],ARRAY['Perfeksionis','Sulit puas'],4500),
('Widodo','Jawa','jv','Yang makmur, yang sejahtera, yang baik','Widodo berasal dari kata Jawa bermakna makmur atau sejahtera. Nama yang mengandung doa agar pemakainya selalu dalam keadaan sejahtera, makmur, dan baik dalam segala urusan kehidupan.','','','L','Jawa','Universal','Jawa',ARRAY['Makmur','Sejahtera','Baik hati','Stabil'],ARRAY['Terlalu nyaman','Kurang ambisius'],5000),
('Bagas','Jawa','jv','Sehat, kuat, gagah perkasa','Bagas berasal dari bahasa Jawa bermakna sehat, kuat, atau gagah. Mengandung doa agar anak selalu sehat jasmani dan rohani serta tumbuh menjadi pribadi yang kuat menghadapi tantangan hidup.','','','L','Jawa','Universal','Jawa',ARRAY['Sehat','Kuat','Aktif','Bersemangat'],ARRAY['Ceroboh','Kurang hati-hati'],5000),
('Gilang','Jawa','jv','Bersinar, cemerlang, gemerlapan','Gilang berasal dari bahasa Jawa bermakna bersinar atau berkilau cemerlang. Melambangkan seseorang yang hidupnya cemerlang, berprestasi tinggi, dan menjadi kebanggaan bagi keluarga dan bangsa.','','','L','Jawa','Universal','Jawa',ARRAY['Cemerlang','Berprestasi','Bersinar','Menginspirasi'],ARRAY['Sombong','Terlalu perfeksionis'],6000),
('Bayu','Jawa','jv','Angin, tiupan angin, yang ringan dan bebas','Bayu berasal dari bahasa Jawa bermakna angin. Dalam mitologi Jawa-Hindu, Bayu adalah nama dewa angin. Melambangkan kebebasan, keringanan jiwa, dan kemampuan menjangkau tempat yang jauh.','','','L','Jawa','Universal','Jawa',ARRAY['Bebas','Ringan','Adaptif','Fleksibel'],ARRAY['Tidak konsisten','Tidak bisa dipegang'],6500),
('Galih','Jawa','jv','Inti kayu, inti sari, kekuatan dari dalam','Galih berasal dari bahasa Jawa bermakna inti kayu atau bagian terkuat dari pohon. Melambangkan kekuatan dari dalam, keteguhan hati, dan esensi sejati yang tidak tergoyahkan tekanan luar.','','','L','Jawa','Universal','Jawa',ARRAY['Kuat dalam','Berprinsip','Teguh','Dapat diandalkan'],ARRAY['Keras kepala','Sulit terbuka'],5000),
('Andika','Jawa','jv','Utusan, pemberitahu, penyampai pesan','Andika berasal dari bahasa Jawa bermakna utusan atau penyampai pesan. Melambangkan seseorang yang menjadi jembatan komunikasi dan perantara kebaikan di tengah masyarakat.','','','L','Jawa','Universal','Jawa',ARRAY['Komunikatif','Jujur','Dapat dipercaya','Berwibawa'],ARRAY['Terlalu banyak bicara','Tidak menjaga rahasia'],6000),
('Tegar','Jawa','jv','Tegar, kuat, tidak goyah, kokoh','Tegar adalah kata Indonesia-Jawa bermakna kuat, kokoh, dan tidak mudah goyah. Mengandung doa agar anak tumbuh menjadi pribadi tangguh yang tidak mudah menyerah menghadapi cobaan.','','','L','Jawa','Universal','Jawa',ARRAY['Kuat','Tangguh','Tidak mudah menyerah','Stabil'],ARRAY['Keras kepala','Sulit minta tolong'],5500),

-- ================================================================
-- NAMA SANSEKERTA / HINDU
-- ================================================================
('Dewi','Sansekerta','sa','Dewi, perempuan ilahi, bersinar seperti dewa','Dewi berasal dari bahasa Sansekerta "devi" bermakna dewi atau perempuan ilahi. Dalam mitologi Hindu, Dewi adalah gelar para dewi. Di Indonesia sangat populer, mengandung makna kemuliaan dan kecantikan.','','','P','Sansekerta','Universal',NULL,ARRAY['Anggun','Mulia','Karismatik','Berwibawa'],ARRAY['Sombong','Kurang membumi'],9000),
('Indra','Sansekerta','sa','Raja para dewa, penguasa langit, yang perkasa','Indra berasal dari bahasa Sansekerta, nama dewa terpenting dalam mitologi Weda, penguasa surga dan dewa petir. Di Indonesia melambangkan kekuatan, kepemimpinan, dan kemegahan.','','','L','Sansekerta','Universal',NULL,ARRAY['Kuat','Pemimpin','Berwibawa','Berani'],ARRAY['Dominan','Otoriter'],7000),
('Rama','Sansekerta','sa','Menyenangkan, yang membuat gembira','Rama berasal dari bahasa Sansekerta "ramya" bermakna menyenangkan. Tokoh utama epos Ramayana, avatar ketujuh Dewa Wisnu, simbol kebenaran dan kebajikan. Sangat populer di Jawa dan Bali.','','','L','Sansekerta','Universal',NULL,ARRAY['Berwibawa','Setia','Berani','Pemimpin'],ARRAY['Kaku pada prinsip','Sulit berkompromi'],6000),
('Candra','Sansekerta','sa','Bulan, cahaya bulan, bersinar terang','Candra berasal dari bahasa Sansekerta bermakna bulan atau cahaya bulan. Dalam mitologi Hindu, Candra adalah dewa bulan. Melambangkan kecantikan, ketenangan, dan cahaya lembut di malam hari.','','','N','Sansekerta','Universal',NULL,ARRAY['Tenang','Indah','Menenangkan','Intuitif'],ARRAY['Moody','Tidak konsisten'],5000),
('Surya','Sansekerta','sa','Matahari, cahaya matahari, sang surya agung','Surya berasal dari bahasa Sansekerta bermakna matahari. Surya adalah dewa matahari dalam mitologi Hindu. Melambangkan kehangatan, kecemerlangan, energi, dan kemampuan menerangi semua makhluk.','','','L','Sansekerta','Universal',NULL,ARRAY['Bersemangat','Hangat','Energik','Menginspirasi'],ARRAY['Terlalu dominan','Tidak sabaran'],6500),
('Arya','Sansekerta','sa','Bangsawan, mulia, terhormat, berbudaya','Arya berasal dari bahasa Sansekerta bermakna bangsawan atau yang mulia. Dalam tradisi Weda, arya merujuk pada kaum berbudaya tinggi dan berperadaban luhur. Mengandung kemuliaan dan martabat.','','','L','Sansekerta','Universal',NULL,ARRAY['Mulia','Terhormat','Berwibawa','Berbudaya'],ARRAY['Sombong','Memandang rendah orang lain'],7000),
('Dian','Sansekerta','sa','Cahaya, lentera, penerangan bagi sekitar','Dian berasal dari kata Jawa-Sansekerta bermakna cahaya atau lentera. Melambangkan seseorang yang menjadi penerang bagi orang lain, membawa cahaya di tengah kegelapan, menginspirasi dengan kehadirannya.','','','P','Sansekerta','Universal',NULL,ARRAY['Bercahaya','Menginspirasi','Cerdas','Hangat'],ARRAY['Terlalu idealis','Mudah kecewa'],6000),
('Putra','Sansekerta','sa','Putra, anak laki-laki, penerus keturunan','Putra berasal dari bahasa Sansekerta bermakna anak laki-laki atau keturunan. Sering digunakan sebagai bagian nama, melambangkan generasi penerus dan harapan keluarga yang besar.','','','L','Sansekerta','Universal',NULL,ARRAY['Penerus','Bertanggung jawab','Berbakti','Mandiri'],ARRAY['Beban ekspektasi','Ekspektasi tinggi'],7000),
('Putri','Sansekerta','sa','Putri, anak perempuan, tuan putri cantik','Putri berasal dari bahasa Sansekerta bermakna anak perempuan atau putri. Nama populer di Indonesia mengandung makna kemuliaan dan kecantikan seorang gadis berharga bagai putri raja.','','','P','Sansekerta','Universal',NULL,ARRAY['Anggun','Mulia','Berharga','Cantik'],ARRAY['Manja','Terlalu memerlukan perhatian'],8000),
('Ayu','Sansekerta','sa','Cantik, elok, berseri-seri','Ayu berasal dari bahasa Bali-Sansekerta bermakna cantik atau elok. Sangat populer untuk perempuan di Jawa dan Bali, melambangkan kecantikan lahir dan batin. Sering dikombinasikan dengan nama lain.','','','P','Sansekerta','Universal',NULL,ARRAY['Cantik','Menarik','Menyenangkan','Berseri'],ARRAY['Terlalu memperhatikan penampilan','Superfisial'],9000),
('Kirana','Sansekerta','sa','Sinar matahari, cahaya yang menerangi','Kirana berasal dari bahasa Sansekerta bermakna sinar atau cahaya matahari. Sangat indah untuk perempuan, melambangkan kecemerlangan dan kemampuan menerangi lingkungan dengan kehadirannya.','','','P','Sansekerta','Universal',NULL,ARRAY['Bercahaya','Cemerlang','Menginspirasi','Hangat'],ARRAY['Terlalu menonjol','Sulit rendah hati'],7500),
('Kusuma','Sansekerta','sa','Bunga, kembang yang indah dan harum','Kusuma berasal dari bahasa Sansekerta bermakna bunga atau kembang. Sangat puitis, digunakan dalam sastra Jawa kuno. Melambangkan keindahan, keharuman, dan keanggunan seperti bunga mekar.','','','P','Sansekerta','Universal',NULL,ARRAY['Indah','Harum','Lembut','Menarik'],ARRAY['Rapuh','Mudah layu'],4000),
('Yoga','Sansekerta','sa','Penghubung, penyatu, keseimbangan jiwa raga','Yoga berasal dari bahasa Sansekerta bermakna menyatukan. Dalam filosofi Hindu, yoga adalah praktik spiritual menyatukan jiwa individu dengan jiwa universal. Melambangkan keseimbangan dan harmoni.','','','L','Sansekerta','Universal',NULL,ARRAY['Seimbang','Tenang','Disiplin','Spiritual'],ARRAY['Terlalu introspektif','Kurang responsif'],5500),
('Raka','Sansekerta','sa','Bulan purnama, yang bersinar penuh sempurna','Raka berasal dari bahasa Sansekerta bermakna bulan purnama. Melambangkan kesempurnaan, kecemerlangan, dan kemampuan menerangi sekitar bagaikan bulan purnama di malam hari.','','','L','Sansekerta','Universal',NULL,ARRAY['Sempurna','Bersinar','Menawan','Penuh'],ARRAY['Moody','Tidak konsisten'],5500),
('Gita','Sansekerta','sa','Lagu, nyanyian, musik yang indah jiwa','Gita berasal dari bahasa Sansekerta bermakna lagu atau nyanyian. Bhagavad Gita adalah teks suci Hindu berbentuk nyanyian ilahi. Melambangkan jiwa penuh musik, harmoni, dan keindahan.','','','P','Sansekerta','Universal',NULL,ARRAY['Artistik','Harmonis','Indah','Ekspresif'],ARRAY['Terlalu emosional','Kurang logis'],5000),
('Ratna','Sansekerta','sa','Permata, batu mulia, yang berharga','Ratna berasal dari bahasa Sansekerta bermakna permata atau batu mulia. Mengandung makna bahwa anak adalah permata berharga bagi keluarga, tak ternilai harganya dan sangat berharga.','','','P','Sansekerta','Universal',NULL,ARRAY['Berharga','Istimewa','Mulia','Cantik'],ARRAY['Rapuh','Perlu penjagaan'],5500),
('Citra','Sansekerta','sa','Citra, gambar yang indah, gambaran jiwa','Citra berasal dari bahasa Sansekerta bermakna gambar atau gambaran indah. Melambangkan seseorang yang memberikan kesan mendalam dan meninggalkan gambaran indah dalam ingatan orang lain.','','','P','Sansekerta','Universal',NULL,ARRAY['Menarik','Berkesan','Kreatif','Artistik'],ARRAY['Terlalu memedulikan citra','Munafik'],6000),
('Satria','Sansekerta','sa','Ksatria, pejuang, kesatria yang mulia','Satria berasal dari bahasa Sansekerta bermakna ksatria atau pejuang mulia. Dalam hierarki Hindu, ksatria adalah kasta pejuang dan pemimpin. Melambangkan keberanian dan kemuliaan jiwa.','','','L','Sansekerta','Universal',NULL,ARRAY['Berani','Mulia','Pemimpin','Pelindung'],ARRAY['Agresif','Terlalu suka konfrontasi'],6000),
('Mahendra','Sansekerta','sa','Indra yang Agung, dewa yang berkuasa besar','Mahendra berasal dari bahasa Sansekerta "maha" (agung) dan "Indra" (raja dewa). Bermakna Indra yang agung atau dewa yang maha berkuasa. Melambangkan keagungan dan kekuatan yang luar biasa.','','','L','Sansekerta','Universal',NULL,ARRAY['Agung','Berkuasa','Pemimpin','Berwibawa'],ARRAY['Otoriter','Sulit merendah'],5000),
('Pradita','Sansekerta','sa','Yang bersinar, yang cemerlang, terang benderang','Pradita berasal dari bahasa Sansekerta bermakna yang bersinar atau cemerlang. Melambangkan seseorang yang selalu tampil cemerlang dan menjadi cahaya penerang bagi orang-orang di sekitarnya.','','','N','Sansekerta','Universal',NULL,ARRAY['Cemerlang','Bersinar','Menginspirasi','Hangat'],ARRAY['Sombong','Sulit rendah hati'],4500),

-- ================================================================
-- NAMA MODERN / INTERNASIONAL POPULER DI INDONESIA
-- ================================================================
('David','Ibrani','he','Yang dicintai, yang tersayang','David berasal dari bahasa Ibrani "Dawid" bermakna yang dicintai. Raja Daud adalah raja paling agung Israel dan seorang nabi. Di Indonesia dipakai lintas agama, melambangkan karisma dan kepemimpinan.','','','L','Modern','Universal',NULL,ARRAY['Dicintai','Karismatik','Berbakat','Pemimpin'],ARRAY['Mudah jatuh cinta','Impulsif'],8000),
('Kevin','Irlandia','ga','Yang tampan, yang terlahir baik','Kevin berasal dari bahasa Irlandia kuno "Caoimhín" bermakna yang tampan dan baik. Populer di Indonesia sejak 1990an, diharapkan tumbuh menjadi pribadi yang baik dan menyenangkan.','','','L','Modern','Universal',NULL,ARRAY['Tampan','Ramah','Menyenangkan','Populer'],ARRAY['Terlalu santai','Kurang serius'],7500),
('Jessica','Ibrani','he','Tuhan melihat, yang melihat dengan penglihatan-Nya','Jessica berasal dari bahasa Ibrani "Yiskah" bermakna Tuhan melihat. Nama populer di kalangan Indonesia modern dan kosmopolitan, melambangkan kecerdasan dan kemandirian.','','','P','Modern','Universal',NULL,ARRAY['Cerdas','Mandiri','Percaya diri','Ambisius'],ARRAY['Terlalu independen','Kurang empati'],6000),
('Tiara','Persia','fa','Mahkota, tiara, yang bermahkota mulia','Tiara berasal dari bahasa Persia bermakna mahkota. Nama anggun untuk perempuan, melambangkan kemuliaan, kecantikan bak putri raja, dan kedudukan terhormat yang menjadi kebanggaan.','','','P','Modern','Universal',NULL,ARRAY['Mulia','Anggun','Berwibawa','Cantik'],ARRAY['Manja','Terlalu bergantung pada status'],6500),
('Zara','Arab','ar','Cahaya, bunga, bersinar cerah','Zara atau Zahrah berasal dari kata Arab bermakna bunga atau cahaya. Nama elegan dan modern, sangat populer di Indonesia dan dunia, melambangkan keindahan dan kecemerlangan jiwa.','زَارَة','Zārah','P','Modern','Universal',NULL,ARRAY['Cantik','Modern','Percaya diri','Menarik'],ARRAY['Terlalu modern','Kurang akar budaya'],8000),
('Farel','Modern','en','Nama modern penuh semangat dan daya tarik','Farel adalah nama modern yang mulai populer di Indonesia. Memberikan kesan dinamis, penuh semangat, dan cocok untuk generasi muda Indonesia yang kosmopolitan dan percaya diri.','','','L','Modern','Universal',NULL,ARRAY['Dinamis','Modern','Percaya diri','Energik'],ARRAY['Impulsif','Kurang sabar'],6000),
('Raffa','Arab','ar','Lembut, menyenangkan, penuh kasih sayang','Raffa berasal dari kata Arab bermakna lembut atau menyenangkan. Nama modern yang sedang tren di Indonesia, melambangkan kelembutan dan keramahan yang membuat nyaman orang di sekitarnya.','رَفَّة','Raffah','N','Modern','Universal',NULL,ARRAY['Lembut','Ramah','Menyenangkan','Hangat'],ARRAY['Terlalu lembut','Mudah dimanfaatkan'],7000),
('Keisha','Modern','en','Favorit, yang dicintai, yang menyenangkan','Keisha adalah nama modern populer di Indonesia bermakna favorit atau yang dicintai. Memberikan kesan hangat, menyenangkan, dan disukai oleh banyak orang di sekitarnya.','','','P','Modern','Universal',NULL,ARRAY['Dicintai','Populer','Hangat','Menyenangkan'],ARRAY['Terlalu ingin disukai','Kurang tegas'],5500),
('Elang','Melayu','ms','Elang, rajawali, terbang tinggi penuh kebebasan','Elang adalah nama Indonesia bermakna burung elang. Melambangkan kebebasan, ketinggian cita-cita, ketajaman visi, dan kekuatan jiwa. Simbol kemuliaan dan keperkasaan di banyak budaya Nusantara.','','','L','Nasional','Universal',NULL,ARRAY['Bebas','Bervisi tinggi','Kuat','Pemimpin'],ARRAY['Sulit diatur','Individualis'],5000),
('Lestari','Jawa','jv','Lestari, abadi, terus-menerus, selalu ada','Lestari berasal dari bahasa Jawa bermakna lestari atau abadi. Mengandung makna keabadian dan keberlangsungan. Sering dikaitkan dengan kelestarian alam dan lingkungan hidup Indonesia.','','','P','Nasional','Universal','Jawa',ARRAY['Setia','Konsisten','Dapat diandalkan','Sabar'],ARRAY['Sulit berubah','Konservatif'],5500),

-- ================================================================
-- NAMA SUNDA
-- ================================================================
('Asep','Sunda','su','Yang baik, yang elok, yang tampan','Asep adalah nama khas Sunda bermakna yang baik atau yang elok. Nama paling populer di kalangan masyarakat Sunda, Jawa Barat. Mengandung harapan sederhana namun tulus agar anak tumbuh menjadi orang yang baik.','','','L','Sunda','Universal','Sunda',ARRAY['Baik hati','Ramah','Sederhana','Tulus'],ARRAY['Terlalu polos','Mudah dimanfaatkan'],7000),
('Ujang','Sunda','su','Anak laki-laki, jejaka, pemuda Sunda','Ujang adalah nama khas Sunda bermakna anak laki-laki atau jejaka muda. Nama sederhana dan akrab di telinga masyarakat Sunda, melambangkan kejujuran dan kesederhanaan yang tulus.','','','L','Sunda','Universal','Sunda',ARRAY['Sederhana','Jujur','Apa adanya','Ramah'],ARRAY['Kurang ambisius','Kurang percaya diri'],5000),
('Neng','Sunda','su','Gadis, anak perempuan, nona manis','Neng adalah kata sapaan khas Sunda untuk anak perempuan atau gadis muda. Nama penuh kasih sayang dan keakraban, melambangkan kelembutan dan keanggunan gadis Sunda yang lembut.','','','P','Sunda','Universal','Sunda',ARRAY['Lembut','Manis','Anggun','Sopan'],ARRAY['Manja','Terlalu bergantung'],4500),
('Dede','Sunda','su','Adik, yang muda, yang disayangi','Dede adalah kata Sunda bermakna adik atau yang lebih muda. Nama yang sangat akrab di telinga masyarakat Sunda, mencerminkan kasih sayang dan kelembutan dalam hubungan kekeluargaan.','','','N','Sunda','Universal','Sunda',ARRAY['Lembut','Disayang','Akrab','Ramah'],ARRAY['Bergantung','Kurang mandiri'],5000),
('Euis','Sunda','su','Cantik, elok, menarik hati','Euis adalah kata Sunda bermakna cantik atau elok. Nama khas wanita Sunda yang singkat namun bermakna indah, melambangkan kecantikan dan keanggunan wanita Sunda yang dikenal lembut.','','','P','Sunda','Universal','Sunda',ARRAY['Cantik','Anggun','Lembut','Menarik'],ARRAY['Manja','Sensitif'],4000),

-- ================================================================
-- NAMA BATAK
-- ================================================================
('Hasibuan','Batak','btk','Marga Batak yang kuat dan terhormat','Hasibuan adalah salah satu marga besar Batak Angkola/Mandailing. Dalam budaya Batak, marga adalah identitas genealogis yang menunjukkan silsilah dan kekerabatan yang kuat dan terhormat.','','','N','Batak','Universal','Batak',ARRAY['Identitas kuat','Setia keluarga','Tangguh','Berprinsip'],ARRAY['Keras kepala','Sulit menerima kritik'],4000),
('Situmorang','Batak','btk','Marga Batak Toba yang gagah perkasa','Situmorang adalah marga Batak Toba yang berasal dari kata bermakna orang yang gagah atau perkasa. Melambangkan keturunan yang kuat, tangguh, dan memiliki tradisi perjuangan yang kuat.','','','N','Batak','Universal','Batak',ARRAY['Gagah','Tangguh','Loyal','Kuat'],ARRAY['Keras','Sulit berkompromi'],3500),
('Pardede','Batak','btk','Marga Batak yang bermakna bapak yang dermawan','Pardede adalah marga Batak bermakna bapak yang pemurah atau dermawan. Melambangkan garis keturunan yang dikenal atas kemurahan hati dan sifat dermawan kepada sesama.','','','N','Batak','Universal','Batak',ARRAY['Dermawan','Pemurah','Setia','Baik hati'],ARRAY['Terlalu murah hati','Mudah dimanfaatkan'],3500),
('Nauli','Batak','btk','Cantik, indah, elok dalam bahasa Batak','Nauli adalah kata Batak bermakna cantik atau indah. Nama yang sering dipakai untuk wanita Batak, melambangkan kecantikan dalam dan luar yang menjadi kebanggaan keluarga dan marga.','','','P','Batak','Universal','Batak',ARRAY['Cantik','Indah','Berbakti','Kuat'],ARRAY['Keras kepala','Sulit diatur'],3000),

-- ================================================================
-- NAMA BUGIS / MAKASSAR
-- ================================================================
('Andi','Bugis','bug','Gelar bangsawan, turunan raja yang mulia','Andi adalah gelar kebangsawanan dalam budaya Bugis-Makassar, Sulawesi Selatan. Menunjukkan garis keturunan bangsawan. Di masa modern menjadi nama sebagai identitas budaya yang dibanggakan.','','','N','Bugis','Universal','Bugis',ARRAY['Bangsawan','Berwibawa','Berbudaya','Dihormati'],ARRAY['Merasa superior','Kurang membumi'],6500),
('Tenri','Bugis','bug','Nama khas Bugis bermakna yang ditunjuk Tuhan','Tenri adalah nama khas Bugis yang bermakna yang ditunjuk atau yang dipilih oleh Tuhan. Sering menjadi awalan nama perempuan Bugis, melambangkan keistimewaan dan pilihan ilahi.','','','P','Bugis','Universal','Bugis',ARRAY['Terpilih','Istimewa','Berwibawa','Dipercaya'],ARRAY['Merasa terpilih','Kurang rendah hati'],3000),

-- ================================================================
-- NAMA MINANGKABAU
-- ================================================================
('Sutan','Minang','ms','Sultan, pemimpin, yang berkuasa','Sutan berasal dari kata Minangkabau bermakna sultan atau pemimpin. Gelar kehormatan adat Minangkabau yang diberikan kepada pria dari garis keturunan bangsawan adat.','','','L','Minang','Universal','Minang',ARRAY['Pemimpin','Berwibawa','Terhormat','Berpengaruh'],ARRAY['Otoriter','Sulit dikoreksi'],4000),
('Puti','Minang','ms','Putri, wanita bangsawan, tuan putri adat','Puti adalah kata Minangkabau bermakna putri atau wanita bangsawan. Gelar kehormatan adat untuk wanita dari garis keturunan bangsawan dalam sistem matrilineal Minangkabau.','','','P','Minang','Universal','Minang',ARRAY['Anggun','Berwibawa','Mulia','Terhormat'],ARRAY['Manja','Bergantung pada status'],3500),
('Dt','Minang','ms','Datuak, gelar adat tertinggi Minangkabau','Datuak adalah gelar adat tertinggi dalam masyarakat Minangkabau, diberikan kepada pemimpin suku. Melambangkan kepemimpinan adat, kebijaksanaan, dan tanggung jawab besar terhadap kaum.','','','L','Minang','Universal','Minang',ARRAY['Pemimpin adat','Bijaksana','Bertanggung jawab','Dihormati'],ARRAY['Terlalu formal','Kaku dalam tradisi'],3000),

-- ================================================================
-- NAMA BALI
-- ================================================================
('Wayan','Bali','ban','Anak pertama dalam urutan Bali','Wayan adalah nama khas Bali untuk anak pertama dalam keluarga (urutan 1 dari 4). Dalam tradisi Bali, nama anak ditentukan berdasarkan urutan lahir. Melambangkan tanggung jawab sebagai sulung.','','','N','Bali','Hindu','Bali',ARRAY['Bertanggung jawab','Pemimpin','Teladan','Mandiri'],ARRAY['Beban sebagai sulung','Terlalu serius'],6000),
('Made','Bali','ban','Anak kedua, yang di tengah','Made adalah nama khas Bali untuk anak kedua atau yang berada di tengah. Dalam filosofi Bali melambangkan keseimbangan, kemampuan menjadi jembatan antara kakak dan adik.','','','N','Bali','Hindu','Bali',ARRAY['Penengah','Seimbang','Diplomatis','Luwes'],ARRAY['Kurang pendirian','Terlalu mengikuti'],5500),
('Nyoman','Bali','ban','Anak ketiga, yang melampaui','Nyoman adalah nama khas Bali untuk anak ketiga. Dalam tradisi Bali dianggap memiliki energi spiritual yang kuat dan sering dipercaya memiliki kemampuan lebih dalam hal intuisi.','','','N','Bali','Hindu','Bali',ARRAY['Intuitif','Spiritual','Kreatif','Unik'],ARRAY['Eksentrik','Sulit dipahami'],5000),
('Ketut','Bali','ban','Anak keempat, si bungsu, yang terakhir','Ketut adalah nama khas Bali untuk anak keempat atau bungsu. Dalam tradisi Bali, anak bungsu sering diperlakukan istimewa dan dianggap membawa keberuntungan bagi keluarga.','','','N','Bali','Hindu','Bali',ARRAY['Beruntung','Disayang','Kreatif','Bebas'],ARRAY['Manja','Kurang mandiri'],4500),
('Agung','Bali','ban','Agung, besar, mulia, yang luhur','Agung berasal dari kata Bali-Sansekerta bermakna agung atau besar. Nama yang sangat dihormati di Bali, sering menjadi bagian dari nama bangsawan Bali. Melambangkan keagungan jiwa.','','','L','Bali','Hindu','Bali',ARRAY['Agung','Mulia','Berwibawa','Dihormati'],ARRAY['Sombong','Sulit merendah'],6000),
('Alit','Bali','ban','Kecil, yang sederhana, yang tawaduk','Alit berasal dari kata Bali bermakna kecil atau sederhana. Nama yang mengandung makna kerendahan hati dan kesederhanaan, berlawanan dengan "agung" namun justru mengandung kemuliaan tersembunyi.','','','N','Bali','Hindu','Bali',ARRAY['Rendah hati','Sederhana','Tulus','Bijaksana'],ARRAY['Kurang percaya diri','Terlalu merendah'],4000);

-- ================================================================
-- TAMBAHAN NAMA POPULER YANG SERING DICARI
-- ================================================================
INSERT INTO nama_dasar
  (nama, asal_bahasa, kode_bahasa, makna_singkat, makna_detail, arti_arab, transliterasi, gender, kategori, agama, suku, sifat_positif, sifat_perhatian, popularitas)
VALUES
('Luthfi','Arab','ar','Lembut, halus, penuh kebaikan','Luthfi berasal dari kata Arab "lutf" bermakna kelembutan, kehalusan, atau kebaikan yang tulus. Al-Latif adalah Asmaul Husna bermakna Maha Lembut. Melambangkan jiwa yang halus dan penuh kasih.','لُطْفِي','Luṭfī','L','Islami','Islam',NULL,ARRAY['Lembut','Halus','Baik hati','Sopan'],ARRAY['Terlalu lembut','Kurang tegas'],5000),
('Zulkifli','Arab','ar','Yang memiliki kelebihan, yang dikaruniai kemampuan','Zulkifli berasal dari kata Arab bermakna yang memiliki kelebihan atau kemampuan. Nama Nabi yang diutus kepada kaumnya di masa Nabi Sulaiman, dikenal atas kesabarannya.','ذُو الْكِفْل','Dhū l-Kifl','L','Islami','Islam',NULL,ARRAY['Sabar','Mampu','Tahan uji','Bijaksana'],ARRAY['Keras kepala','Sulit menyerah'],4000),
('Naufan','Arab','ar','Lautan yang dalam dan luas','Naufan berasal dari kata Arab bermakna lautan yang dalam. Melambangkan kedalaman ilmu, luasnya wawasan, dan ketenangan jiwa bagaikan samudra yang luas dan dalam.','نَوْفَان','Nawfān','L','Islami','Islam',NULL,ARRAY['Dalam','Luas wawasan','Tenang','Bijaksana'],ARRAY['Misterius','Sulit dipahami'],3500),
('Azzam','Arab','ar','Tekad yang kuat, niat yang bulat','Azzam berasal dari kata Arab "azama" bermakna tekad atau niat yang kuat. Melambangkan seseorang yang memiliki tekad baja dan niat yang tidak mudah goyah dalam mengejar tujuannya.','عَزَّام','ʿAzzām','L','Islami','Islam',NULL,ARRAY['Bertekad','Gigih','Tidak menyerah','Fokus'],ARRAY['Keras kepala','Sulit berkompromi'],5000),
('Khoirul','Arab','ar','Yang terbaik, yang paling baik','Khoirul berasal dari kata Arab "khayru" bermakna yang terbaik. Sering dikombinasikan dengan kata lain: Khoirul Anam (sebaik makhluk), Khoirul Ummah (sebaik umat). Doa untuk menjadi yang terbaik.','خَيْرُ','Khayr','L','Islami','Islam',NULL,ARRAY['Terbaik','Unggul','Mulia','Berpengaruh'],ARRAY['Ekspektasi tinggi','Beban menjadi yang terbaik'],4500),
('Habib','Arab','ar','Yang dicintai, kekasih, yang dekat di hati','Habib berasal dari kata Arab "habba" bermakna cinta atau sayang. Habib Allah bermakna kekasih Allah. Gelar kemuliaan untuk keturunan Nabi yang mengandung makna cinta yang tulus.','حَبِيب','Ḥabīb','L','Islami','Islam',NULL,ARRAY['Dicintai','Karismatik','Hangat','Penuh kasih'],ARRAY['Terlalu bergantung pada cinta','Sensitif'],5000),
('Hanif','Arab','ar','Yang lurus, yang cenderung pada kebenaran','Hanif berasal dari kata Arab bermakna yang lurus atau yang cenderung pada kebenaran dan kebaikan. Dalam Islam, hanif adalah orang yang fitrahnya cenderung kepada tauhid dan kebenaran.','حَنِيف','Ḥanīf','L','Islami','Islam',NULL,ARRAY['Lurus','Beriman','Teguh','Tulus'],ARRAY['Kaku','Sulit menerima perbedaan'],4500),
('Nizar','Arab','ar','Yang kecil dan lembut, peringatan','Nizar berasal dari kata Arab bermakna kecil dan lembut, atau peringatan. Nama yang mengandung makna kehalusan jiwa sekaligus kemampuan memberikan peringatan yang bijak.','نِزَار','Nizār','L','Islami','Islam',NULL,ARRAY['Lembut','Bijak','Peringatan','Halus'],ARRAY['Terlalu kritis','Mudah menghakimi'],3500),
('Rafiq','Arab','ar','Teman, sahabat, yang lemah lembut','Rafiq berasal dari kata Arab bermakna teman, sahabat, atau yang lemah lembut. Al-Rafiq adalah Asmaul Husna. Melambangkan persahabatan yang tulus dan kelembuatan dalam berinteraksi.','رَفِيق','Rafīq','L','Islami','Islam',NULL,ARRAY['Ramah','Bersahabat','Lembut','Setia'],ARRAY['Terlalu baik','Mudah dimanfaatkan'],4000),
('Syauqi','Arab','ar','Kerinduan, rasa rindu yang mendalam','Syauqi berasal dari kata Arab "syauq" bermakna kerinduan atau rasa rindu. Melambangkan jiwa yang selalu merindukan kebaikan, kebenaran, dan keindahan sejati dalam setiap aspek kehidupan.','شَوْقِي','Shawqī','L','Islami','Islam',NULL,ARRAY['Penuh perasaan','Romantis','Seni tinggi','Mendalam'],ARRAY['Terlalu emosional','Melankolis'],3500),
('Firman','Jawa','jv','Firman, titah, perintah yang luhur','Firman berasal dari kata Arab-Melayu bermakna perintah atau titah yang luhur. Mengandung makna bahwa sang anak membawa firman atau titah kebenaran dalam hidupnya dan menjadi perintis kebaikan.','','','L','Nasional','Universal','Jawa',ARRAY['Berwibawa','Tegas','Pemimpin','Berpengaruh'],ARRAY['Otoriter','Sulit dikoreksi'],6000),
('Hendra','Sansekerta','sa','Indra yang agung, pemimpin yang hebat','Hendra berasal dari bahasa Sansekerta yang merupakan gabungan dari kata yang bermakna Indra yang agung. Melambangkan kepemimpinan yang kuat dan kemampuan yang luar biasa dalam berbagai bidang.','','','L','Sansekerta','Universal',NULL,ARRAY['Pemimpin','Kuat','Cerdas','Berpengaruh'],ARRAY['Dominan','Sulit berbagi kuasa'],5500),
('Gunawan','Jawa','jv','Orang yang berguna, yang memiliki kegunaan','Gunawan berasal dari kata Jawa "guna" (berguna) dan akhiran "-wan" (orang). Mengandung harapan agar anak tumbuh menjadi orang yang berguna bagi keluarga, masyarakat, dan bangsanya.','','','L','Jawa','Universal','Jawa',ARRAY['Berguna','Bermanfaat','Produktif','Bertanggung jawab'],ARRAY['Workaholic','Lupa beristirahat'],5000),
('Suryadi','Jawa','jv','Sinar matahari, yang bersinar sepanjang hari','Suryadi berasal dari gabungan kata Sansekerta "surya" (matahari) dan akhiran Jawa. Melambangkan seseorang yang senantiasa bersinar dan memberi kehangatan layaknya matahari yang tidak pernah padam.','','','L','Jawa','Universal','Jawa',ARRAY['Bersemangat','Hangat','Konsisten','Energik'],ARRAY['Terlalu bersemangat','Kurang istirahat'],4500),
('Kristanto','Jawa','jv','Pengikut Kristus yang terpilih, orang Kristen','Kristanto adalah nama Jawa-Kristen yang berasal dari kata "Kristus" dengan akhiran Jawa. Melambangkan iman Kristen yang dipadukan dengan identitas budaya Jawa yang kuat dan harmonis.','','','L','Modern','Kristen','Jawa',ARRAY['Beriman','Harmonis','Setia','Bermoral'],ARRAY['Kaku dalam iman','Sulit menerima perbedaan'],4000),
('Cahyo','Jawa','jv','Cahaya, sinar, terang benderang','Cahyo berasal dari kata Jawa bermakna cahaya atau sinar. Melambangkan seseorang yang membawa cahaya dan penerangan bagi lingkungan sekitarnya, menjadi harapan dan inspirasi bagi orang lain.','','','L','Jawa','Universal','Jawa',ARRAY['Bercahaya','Menginspirasi','Hangat','Positif'],ARRAY['Terlalu menonjol','Sulit rendah hati'],5000),
('Sekar','Jawa','jv','Bunga, kembang yang indah dan harum','Sekar berasal dari kata Jawa bermakna bunga atau kembang. Nama khas untuk perempuan Jawa, melambangkan keindahan, keharuman, dan kecantikan bak bunga yang mekar di musim semi.','','','P','Jawa','Universal','Jawa',ARRAY['Indah','Harum','Lembut','Menarik'],ARRAY['Rapuh','Mudah layu'],5000),
('Wulandari','Jawa','jv','Bulan bintang yang indah, cahaya malam','Wulandari berasal dari kata Jawa "wulan" (bulan) dan "dari" (yang indah). Melambangkan keindahan seorang wanita yang bercahaya lembut bagaikan bulan di malam hari yang menerangi kegelapan.','','','P','Jawa','Universal','Jawa',ARRAY['Indah','Lembut','Anggun','Menenangkan'],ARRAY['Moody','Tidak konsisten'],5500),
('Suci','Jawa','jv','Suci, bersih, murni, tidak ternoda','Suci berasal dari kata Jawa-Melayu bermakna suci, bersih, atau murni. Melambangkan kemurnian hati dan jiwa yang bersih dari segala kenistaan. Nama yang mengandung harapan tertinggi orang tua.','','','P','Nasional','Universal',NULL,ARRAY['Suci','Bersih','Murni','Tulus'],ARRAY['Naif','Tidak siap dengan keburukan dunia'],5000),
('Yuli','Jawa','jv','Lahir di bulan Juli, penuh semangat musim panas','Yuli adalah nama yang merujuk pada bulan Juli. Melambangkan semangat, kehangatan, dan keceriaan. Di Indonesia menjadi nama perempuan yang populer, melambangkan keceriaan dan keterbukaan.','','','P','Modern','Universal',NULL,ARRAY['Ceria','Terbuka','Hangat','Semangat'],ARRAY['Impulsif','Kurang sabar'],4500);

-- ================================================================
-- SELESAI — Database siap dengan 200+ nama seed
-- Sistem AI akan auto-generate nama yang belum ada
-- ================================================================
